
public void button1_click1(GButton source, GEvent event) { //_CODE_:button1:933590:
    window1.setVisible(true);
  
} //_CODE_:button1:933590:

public void button2_click1(GButton source, GEvent event) { //_CODE_:button2:481432:
    window2.setVisible(true);
} //_CODE_:button2:481432:

public void button3_click1(GButton source, GEvent event) { //_CODE_:button3:314583:
     window3.setVisible(true);
} //_CODE_:button3:314583:

public void button4_click1(GButton source, GEvent event) { //_CODE_:button4:840528:
 window4.setVisible(true);
} //_CODE_:button4:840528:

public void button5_click1(GButton source, GEvent event) { //_CODE_:button5:897121:
  window5.setVisible(true);
} //_CODE_:button5:897121:

public void button6_click1(GButton source, GEvent event) { //_CODE_:button6:537210:
  window6.setVisible(true);
} //_CODE_:button6:537210:

synchronized public void win_draw6(PApplet appc, GWinData data) { //_CODE_:window1:276956:
  appc.background(#E6E6FA);
} //_CODE_:window1:276956:

public void textfield1_change1(GTextField  source, GEvent event) { //_CODE_:textfield1:596590: 

 words=source.getText();
 
} //_CODE_:textfield1:596590:


public void dropList1_click1(GDropList source, GEvent event) { //_CODE_:Style:446481:
if(source.getSelectedIndex()==0){
  Typo_pixel = false;
  Typo_dot = true;
  Typo_illusion = false;
}

if(source.getSelectedIndex()==1){
  Typo_pixel = true;
  Typo_dot = false;
  Typo_illusion = false;
}

if(source.getSelectedIndex()==2){
  Typo_pixel = false;
  Typo_dot = false;
  Typo_illusion = true;
}

} //_CODE_:Style:446481:

public void slider1_change1(GSlider source, GEvent event) { //_CODE_:TextSize:705696:
  textsize= source.getValueI();
} //_CODE_:TextSize:705696:

public void button7_click1(GButton source, GEvent event) { //_CODE_:button7:405410:
   window1.setVisible(false);
} //_CODE_:button7:405410:

synchronized public void win_draw1(PApplet appc, GWinData data) { //_CODE_:window2:873295:
  appc.background(#E6E6FA);

} //_CODE_:window2:873295:

public void dropList1_click2(GDropList source, GEvent event) { //_CODE_:Brush:624212:
if(source.getSelectedIndex()==0){
circle=true;
sticks=false;
}

if(source.getSelectedIndex()==1){
circle=false;
sticks=true;
}

} //_CODE_:Brush:624212:

public void button8_click1(GButton source, GEvent event) { //_CODE_:button8:355258:
 window2.setVisible(false);
} //_CODE_:button8:355258:

public void slider1_change2(GSlider source, GEvent event) { //_CODE_:slider1:553976:
easing  = source.getValueF();
} //_CODE_:slider1:553976:

synchronized public void win_draw2(PApplet appc, GWinData data) { //_CODE_:window3:935631:
  appc.background(#E6E6FA);
  
} //_CODE_:window3:935631:

public void textfield2_change1(GTextField source, GEvent event) { //_CODE_:textfield2:396777:
  println("textfield2 - GTextField >> GEvent." + event + " @ " + millis());
} //_CODE_:textfield2:396777:

public void dropList1_click3(GDropList source, GEvent event) { //_CODE_:process_method:296623:
 
} //_CODE_:process_method:296623:

public void button9_click1(GButton source, GEvent event) { //_CODE_:button9:649339:
   
} //_CODE_:button9:649339:

public void button10_click1(GButton source, GEvent event) { //_CODE_:button10:498971:
  window3.setVisible(false);
} //_CODE_:button10:498971:

synchronized public void win_draw3(PApplet appc, GWinData data) { //_CODE_:window4:584340:
  appc.background(#E6E6FA);
} //_CODE_:window4:584340:

public void button11_click1(GButton source, GEvent event) { //_CODE_:button11:461170:
  window4.setVisible(false);
} //_CODE_:button11:461170:

synchronized public void win_draw4(PApplet appc, GWinData data) { //_CODE_:window5:741172:
  appc.background(#E6E6FA);
} //_CODE_:window5:741172:

public void button12_click1(GButton source, GEvent event) { //_CODE_:button12:670796:
  window5.setVisible(false);
} //_CODE_:button12:670796:

synchronized public void win_draw5(PApplet appc, GWinData data) { //_CODE_:window6:316803:
  appc.background(#E6E6FA);
} //_CODE_:window6:316803:

public void button13_click1(GButton source, GEvent event) { //_CODE_:button13:763028:
 window6.setVisible(false);
} //_CODE_:button13:763028:

public void button14_click1(GButton source, GEvent event) { //_CODE_:button13:763028:
  clear=true;
  
} //_CODE_:button13:763028:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Main funcion");
  button1 = new GButton(this, 120, 200, 150, 80);
  button1.setIcon("s.png", 1, GAlign.NORTH, GAlign.CENTER, GAlign.MIDDLE);
  button1.setText("Typography");
  button1.setLocalColorScheme(GCScheme.GOLD_SCHEME);
  button1.addEventHandler(this, "button1_click1");
  button2 = new GButton(this, 320, 200, 150, 80);
  button2.setIcon("z.png", 1, GAlign.NORTH, GAlign.CENTER, GAlign.BOTTOM);
  button2.setText("Brush");
  button2.setLocalColorScheme(GCScheme.CYAN_SCHEME);
  button2.addEventHandler(this, "button2_click1");
  button3 = new GButton(this, 520, 200, 150, 80);
  button3.setIcon("z2.png", 1, GAlign.NORTH, GAlign.CENTER, GAlign.MIDDLE);
  button3.setText("Pictures");
  button3.setLocalColorScheme(GCScheme.RED_SCHEME);
  button3.addEventHandler(this, "button3_click1");
  button4 = new GButton(this, 120, 340, 150, 80);
  button4.setIcon("z3.png", 1, GAlign.NORTH, GAlign.CENTER, GAlign.MIDDLE);
  button4.setTextAlign(GAlign.CENTER, GAlign.EAST);
  button4.setText("MusicViz");
  button4.setLocalColorScheme(GCScheme.RED_SCHEME);
  button4.addEventHandler(this, "button4_click1");
  button5 = new GButton(this, 320, 340, 150, 80);
  button5.setIcon("z4.png", 1, GAlign.NORTH, GAlign.CENTER, GAlign.MIDDLE);
  button5.setText("3DGraphics");
  button5.setLocalColorScheme(GCScheme.GOLD_SCHEME);
  button5.addEventHandler(this, "button5_click1");
  button6 = new GButton(this, 520, 340, 150, 80);
  button6.setIcon("z5.png", 1, GAlign.NORTH, GAlign.CENTER, GAlign.MIDDLE);
  button6.setText("Help");
  button6.setLocalColorScheme(GCScheme.CYAN_SCHEME);
  button6.addEventHandler(this, "button6_click1");
  window1 = GWindow.getWindow(this, "Window title", 0, 0, 1920, 1080, JAVA2D);
  window1.noLoop();
  window1.setActionOnClose(G4P.EXIT_APP);
  window1.addDrawHandler(this, "win_draw1");
   window1.addDrawHandler(this, "win_draw11");
  textfield1 = new GTextField(window1, 10, 10, 400, 40, G4P.SCROLLBARS_NONE);
  textfield1.setLocalColorScheme(GCScheme.GOLD_SCHEME);
  textfield1.setOpaque(true);
  textfield1.addEventHandler(this, "textfield1_change1");
  Style = new GDropList(window1, 1800, 10, 90, 80, 3, 10);
  Style.setItems(loadStrings("list_446481"), 0);
  Style.setLocalColorScheme(GCScheme.GOLD_SCHEME);
  Style.addEventHandler(this, "dropList1_click1");
  TextSize = new GSlider(window1, 760, 1000, 400, 50, 20.0);
  TextSize.setShowValue(true);
  TextSize.setShowLimits(true);
  TextSize.setLimits(400, 64, 800);
  TextSize.setNumberFormat(G4P.INTEGER, 0);
  TextSize.setLocalColorScheme(GCScheme.GOLD_SCHEME);
  TextSize.setOpaque(false);
  TextSize.addEventHandler(this, "slider1_change1");
  button7 = new GButton(window1, 1800, 1010, 80, 30);
  button7.setText("EXIT");
  button7.setLocalColorScheme(GCScheme.GOLD_SCHEME);
  button7.addEventHandler(this, "button7_click1");
  window2 = GWindow.getWindow(this, "Window title", 0, 0, 1920, 1080, JAVA2D);
  window2.noLoop();
  window2.setActionOnClose(G4P.EXIT_APP);
  window2.addDrawHandler(this, "win_draw6");
    window2.addDrawHandler(this, "win_draw22");
  Brush = new GDropList(window2, 10, 15, 90, 80, 2, 10);
  Brush.setItems(loadStrings("list_624212"), 0);
  Brush.setLocalColorScheme(GCScheme.CYAN_SCHEME);
  Brush.addEventHandler(this, "dropList1_click2");
  button8 = new GButton(window2, 1800, 1010, 80, 30);
  button8.setText("EXIT");
  button8.setLocalColorScheme(GCScheme.CYAN_SCHEME);
  button8.addEventHandler(this, "button8_click1");
   button14 = new GButton(window2, 10, 1010, 80, 30);
  button14.setText("CLEAR");
  button14.setLocalColorScheme(GCScheme.CYAN_SCHEME);
  button14.addEventHandler(this, "button14_click1");
  slider1 = new GSlider(window2, 1600, 10, 250, 60, 20.0);
  slider1.setShowValue(true);
  slider1.setShowLimits(true);
  slider1.setLimits(0.01, 0.01, 2);
  slider1.setNumberFormat(G4P.DECIMAL, 0);
  slider1.setLocalColorScheme(GCScheme.CYAN_SCHEME);
  slider1.setOpaque(false);
  slider1.addEventHandler(this, "slider1_change2");
  window3 = GWindow.getWindow(this, "Window title", 0, 0, 1920, 1080, JAVA2D);
  window3.noLoop();
  window3.setActionOnClose(G4P.EXIT_APP);
  window3.addDrawHandler(this, "win_draw2");
  textfield2 = new GTextField(window3, 10, 10, 400, 40, G4P.SCROLLBARS_NONE);
  textfield2.setText("input picture's URL");
  textfield2.setLocalColorScheme(GCScheme.RED_SCHEME);
  textfield2.setOpaque(true);
  textfield2.addEventHandler(this, "textfield2_change1");
  process_method = new GDropList(window3, 1720, 10, 150, 80, 3, 10);
  process_method.setItems(loadStrings("list_296623"), 0);
  process_method.setLocalColorScheme(GCScheme.RED_SCHEME);
  process_method.addEventHandler(this, "dropList1_click3");
  button9 = new GButton(window3, 440, 15, 80, 30);
  button9.setText("Input");
  button9.setLocalColorScheme(GCScheme.RED_SCHEME);
  button9.addEventHandler(this, "button9_click1");
  button10 = new GButton(window3, 1800, 1010, 80, 30);
  button10.setText("EXIT");
  button10.setLocalColorScheme(GCScheme.RED_SCHEME);
  button10.addEventHandler(this, "button10_click1");
  window4 = GWindow.getWindow(this, "Window title", 0, 0, 1920, 1080, JAVA2D);
  window4.noLoop();
  window4.setActionOnClose(G4P.EXIT_APP);
  window4.addDrawHandler(this, "win_draw3");
  button11 = new GButton(window4, 1800, 1010, 80, 30);
  button11.setText("EXIT");
  button11.setLocalColorScheme(GCScheme.RED_SCHEME);
  button11.addEventHandler(this, "button11_click1");
  window5 = GWindow.getWindow(this, "Window title", 0, 0, 1920, 1080, P3D);
  window5.noLoop();
  window5.setActionOnClose(G4P.EXIT_APP);
  window5.addDrawHandler(this, "win_draw4");
  button12 = new GButton(window5, 1800, 1010, 80, 30);
  button12.setText("EXIT");
  button12.setLocalColorScheme(GCScheme.GOLD_SCHEME);
  button12.addEventHandler(this, "button12_click1");
  window6 = GWindow.getWindow(this, "Window title", 0, 0, 800, 600, JAVA2D);
  window6.noLoop();
  window6.setActionOnClose(G4P.EXIT_APP);
  window6.addDrawHandler(this, "win_draw5");
  button13 = new GButton(window6, 700, 550, 80, 30);
  button13.setText("EXIT");
  button13.setLocalColorScheme(GCScheme.CYAN_SCHEME);
  button13.addEventHandler(this, "button13_click1");
  window1.loop();
  window2.loop();
  window3.loop();
  window4.loop();
  window5.loop();
  window6.loop();
    window1.setAlwaysOnTop(true);
  window1.setVisible(false);
    window2.setAlwaysOnTop(true);
  window2.setVisible(false);
    window3.setAlwaysOnTop(true);
  window3.setVisible(false);
    window4.setAlwaysOnTop(true);
  window4.setVisible(false);
    window5.setAlwaysOnTop(true);
  window5.setVisible(false);
    window6.setAlwaysOnTop(true);
  window6.setVisible(false);
}

// Variable declarations 
// autogenerated do not edit
GButton button1; 
GButton button2; 
GButton button3; 
GButton button4; 
GButton button5; 
GButton button6; 
GWindow window1;
GTextField textfield1; 
GDropList Style; 
GSlider TextSize; 
GButton button7; 
GWindow window2;
GDropList Brush; 
GButton button8; 
GSlider slider1; 
GWindow window3;
GTextField textfield2; 
GDropList process_method; 
GButton button9; 
GButton button10; 
GWindow window4;
GButton button11; 
GWindow window5;
GButton button12; 
GWindow window6;
GButton button13; 
GButton button14; 
